// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX3QIKH4lLoFOTwy6pSEXB8UPZ8azu1Xc',
    appId: '1:114149785250:android:1e273a98fbb4c2131d61fb',
    messagingSenderId: '114149785250',
    projectId: 'b21-project',
    databaseURL: 'https://b21-project-default-rtdb.firebaseio.com',
    storageBucket: 'b21-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-McHTzF2TdtQdXZmsBKFRw5E8jEJiWOM',
    appId: '1:114149785250:ios:d035f68474bda97e1d61fb',
    messagingSenderId: '114149785250',
    projectId: 'b21-project',
    databaseURL: 'https://b21-project-default-rtdb.firebaseio.com',
    storageBucket: 'b21-project.appspot.com',
    androidClientId: '114149785250-0ph1etl3sapgfujsq3s72u5q0lpku4mg.apps.googleusercontent.com',
    iosClientId: '114149785250-bk044m3bv8a5o2kdbfop5qv07534u0lf.apps.googleusercontent.com',
    iosBundleId: 'br.com.b21.driver',
  );

}